// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPDSjudgeB.data;

#nullable disable

namespace UPDSjudgeB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPDSjudgeB.Models.CasoPrueba", b =>
                {
                    b.Property<int>("idCasoPrueba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCasoPrueba"));

                    b.Property<string>("entrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idProblema")
                        .HasColumnType("integer");

                    b.Property<string>("salida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idCasoPrueba");

                    b.HasIndex("idProblema");

                    b.ToTable("CasosPrueba");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Concurso", b =>
                {
                    b.Property<int>("idConcurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idConcurso"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contrasena")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idUsuarioCreador")
                        .HasColumnType("integer");

                    b.Property<int>("minutosCongelamiento")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("urlSetProblemas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idConcurso");

                    b.HasIndex("idUsuarioCreador");

                    b.ToTable("Concursos");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Envio", b =>
                {
                    b.Property<int>("idEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEnvio"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idLenguaje")
                        .HasColumnType("integer");

                    b.Property<int>("idProblema")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("memoria")
                        .HasColumnType("integer");

                    b.Property<string>("resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("tiempo")
                        .HasColumnType("real");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("upsolving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEnvio");

                    b.HasIndex("idLenguaje");

                    b.HasIndex("idProblema");

                    b.HasIndex("idUsuario");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Lenguaje", b =>
                {
                    b.Property<int>("idLenguaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idLenguaje"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idJudge0")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idLenguaje");

                    b.ToTable("Lenguajes");

                    b.HasData(
                        new
                        {
                            idLenguaje = 1,
                            estado = "Activo",
                            extension = "cpp",
                            idJudge0 = 54,
                            nombre = "C++ (GCC 9.2.0)"
                        },
                        new
                        {
                            idLenguaje = 2,
                            estado = "Activo",
                            extension = "py",
                            idJudge0 = 71,
                            nombre = "Python (3.8.1)"
                        },
                        new
                        {
                            idLenguaje = 3,
                            estado = "Activo",
                            extension = "cs",
                            idJudge0 = 51,
                            nombre = "C# (Mono 6.6.0.161)"
                        });
                });

            modelBuilder.Entity("UPDSjudgeB.Models.ParticipanteConcurso", b =>
                {
                    b.Property<int>("idParticipanteConcurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idParticipanteConcurso"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idConcurso")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.HasKey("idParticipanteConcurso");

                    b.HasIndex("idConcurso");

                    b.HasIndex("idUsuario", "idConcurso")
                        .IsUnique();

                    b.ToTable("ParticipantesConcursos");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Problema", b =>
                {
                    b.Property<int>("idProblema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idProblema"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idConcurso")
                        .HasColumnType("integer");

                    b.Property<char>("inciso")
                        .HasColumnType("character(1)");

                    b.Property<int>("memoria")
                        .HasColumnType("integer");

                    b.Property<float>("tiempo")
                        .HasColumnType("real");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idProblema");

                    b.HasIndex("idConcurso");

                    b.ToTable("Problemas");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Rol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idRol"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            idRol = 1,
                            nombre = "AdministradorRoles"
                        },
                        new
                        {
                            idRol = 2,
                            nombre = "AdministradorConcursos"
                        },
                        new
                        {
                            idRol = 3,
                            nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idUsuario");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            contrasena = "$2a$11$lHroH6rOVBeO6wtdG9F0ouo3.7i3HNXiuNXtTcykjDO2tKsGtc7kS",
                            correo = "wilsonyucra413@gmail.com",
                            estado = "Activo",
                            fechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            nombre = "Wilson"
                        });
                });

            modelBuilder.Entity("UPDSjudgeB.Models.UsuarioRol", b =>
                {
                    b.Property<int>("idUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsuarioRol"));

                    b.Property<int>("idRol")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.HasKey("idUsuarioRol");

                    b.HasIndex("idRol");

                    b.HasIndex("idUsuario");

                    b.ToTable("UsuarioRoles");

                    b.HasData(
                        new
                        {
                            idUsuarioRol = 1,
                            idRol = 1,
                            idUsuario = 1
                        },
                        new
                        {
                            idUsuarioRol = 2,
                            idRol = 2,
                            idUsuario = 1
                        },
                        new
                        {
                            idUsuarioRol = 3,
                            idRol = 3,
                            idUsuario = 1
                        });
                });

            modelBuilder.Entity("UPDSjudgeB.Models.CasoPrueba", b =>
                {
                    b.HasOne("UPDSjudgeB.Models.Problema", "Problema")
                        .WithMany("CasosPrueba")
                        .HasForeignKey("idProblema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problema");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Concurso", b =>
                {
                    b.HasOne("UPDSjudgeB.Models.Usuario", "Creador")
                        .WithMany("ConcursosCreados")
                        .HasForeignKey("idUsuarioCreador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Envio", b =>
                {
                    b.HasOne("UPDSjudgeB.Models.Lenguaje", "Lenguaje")
                        .WithMany("Envios")
                        .HasForeignKey("idLenguaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPDSjudgeB.Models.Problema", "Problema")
                        .WithMany("Envios")
                        .HasForeignKey("idProblema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPDSjudgeB.Models.Usuario", "Usuario")
                        .WithMany("Envios")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lenguaje");

                    b.Navigation("Problema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.ParticipanteConcurso", b =>
                {
                    b.HasOne("UPDSjudgeB.Models.Concurso", "Concurso")
                        .WithMany("Participantes")
                        .HasForeignKey("idConcurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPDSjudgeB.Models.Usuario", "Usuario")
                        .WithMany("Participaciones")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concurso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Problema", b =>
                {
                    b.HasOne("UPDSjudgeB.Models.Concurso", "Concurso")
                        .WithMany("Problemas")
                        .HasForeignKey("idConcurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concurso");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.UsuarioRol", b =>
                {
                    b.HasOne("UPDSjudgeB.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPDSjudgeB.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Concurso", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Problemas");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Lenguaje", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Problema", b =>
                {
                    b.Navigation("CasosPrueba");

                    b.Navigation("Envios");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("UPDSjudgeB.Models.Usuario", b =>
                {
                    b.Navigation("ConcursosCreados");

                    b.Navigation("Envios");

                    b.Navigation("Participaciones");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
